name: Deploy

on:
  push:
    branches:
      - main
      - feat/usbe-0002/infra
    paths:
      - '.github/workflows/deploy.yml'
      - 'url-shortener-be/**'

env:
  AWS_REGION: ap-southeast-1
  DOCKER_REPO: urlshortener-be
  TF_VAR_db_user: ${{ secrets.DB_USER }}
  TF_VAR_db_pass: ${{ secrets.DB_PASS }}

permissions:
  id-token: write
  contents: read

jobs:
  infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339712725134:role/asdf
          role-session-name: gha-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform
        working-directory: ./infra
        run: terraform init

      - name: Apply Terraform (auto-approve)
        working-directory: ./infra
        run: |
          terraform apply -auto-approve

  urlshortener-be:
    runs-on: ubuntu-latest
    needs: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest

      - name: Deploy Rails Application
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ steps.terraform.outputs.ec2_public_ip.value }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest
            sudo docker run -d -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/my-rails-app:latest
